/*
 * Bierwart API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BierwartApi);
  }
}(this, function(expect, BierwartApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BierwartApi.UserApi();
  });

  describe('(package)', function() {
    describe('UserApi', function() {
      describe('04e93a83a654f3363c92504b78cc5731', function() {
        it('should call 04e93a83a654f3363c92504b78cc5731 successfully', function(done) {
          // TODO: uncomment 04e93a83a654f3363c92504b78cc5731 call and complete the assertions
          /*

          instance.04e93a83a654f3363c92504b78cc5731(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BierwartApi.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('6e06ce11ef408cb43bd0448d5ced6a75', function() {
        it('should call 6e06ce11ef408cb43bd0448d5ced6a75 successfully', function(done) {
          // TODO: uncomment, update parameter values for 6e06ce11ef408cb43bd0448d5ced6a75 call
          /*

          instance.6e06ce11ef408cb43bd0448d5ced6a75(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
