/*
 * Bierwart API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {CreateUserBody} from '../model/CreateUserBody';
import {InlineResponse2001} from '../model/InlineResponse2001';

/**
* User service.
* @module api/UserApi
* @version 0.1
*/
export class UserApi {

    /**
    * Constructs a new UserApi. 
    * @alias module:api/UserApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the 04e93a83a654f3363c92504b78cc5731 operation.
     * @callback moduleapi/UserApi~04e93a83a654f3363c92504b78cc5731Callback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns a list of all users in the database
     * @param {module:api/UserApi~04e93a83a654f3363c92504b78cc5731Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    04e93a83a654f3363c92504b78cc5731(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/useroverview', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the 6e06ce11ef408cb43bd0448d5ced6a75 operation.
     * @callback moduleapi/UserApi~6e06ce11ef408cb43bd0448d5ced6a75Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * An administrator adds a user and creates an account, if wanted
     * Füge einen Nutzer hinzu und erstelle einen passenden Account, falls gewünscht
     * @param {module:model/CreateUserBody} body 
     * @param {module:api/UserApi~6e06ce11ef408cb43bd0448d5ced6a75Callback} callback The callback function, accepting three arguments: error, data, response
     */
    6e06ce11ef408cb43bd0448d5ced6a75(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling 6e06ce11ef408cb43bd0448d5ced6a75");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['auth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/createUser', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}