/*
 * Bierwart API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {CreateAccountMovementBody} from './model/CreateAccountMovementBody';
import {CreateBeverageBody} from './model/CreateBeverageBody';
import {CreateDrinkTypeBody} from './model/CreateDrinkTypeBody';
import {CreateUserBody} from './model/CreateUserBody';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse2001Data} from './model/InlineResponse2001Data';
import {InlineResponse200Data} from './model/InlineResponse200Data';
import {OrderBeverageBody} from './model/OrderBeverageBody';
import {AccountsApi} from './api/AccountsApi';
import {BeverageApi} from './api/BeverageApi';
import {BierwartApi} from './api/BierwartApi';
import {UserApi} from './api/UserApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BierwartApi = require('index'); // See note below*.
* var xxxSvc = new BierwartApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BierwartApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BierwartApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BierwartApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateAccountMovementBody model constructor.
     * @property {module:model/CreateAccountMovementBody}
     */
    CreateAccountMovementBody,

    /**
     * The CreateBeverageBody model constructor.
     * @property {module:model/CreateBeverageBody}
     */
    CreateBeverageBody,

    /**
     * The CreateDrinkTypeBody model constructor.
     * @property {module:model/CreateDrinkTypeBody}
     */
    CreateDrinkTypeBody,

    /**
     * The CreateUserBody model constructor.
     * @property {module:model/CreateUserBody}
     */
    CreateUserBody,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2001Data model constructor.
     * @property {module:model/InlineResponse2001Data}
     */
    InlineResponse2001Data,

    /**
     * The InlineResponse200Data model constructor.
     * @property {module:model/InlineResponse200Data}
     */
    InlineResponse200Data,

    /**
     * The OrderBeverageBody model constructor.
     * @property {module:model/OrderBeverageBody}
     */
    OrderBeverageBody,

    /**
    * The AccountsApi service constructor.
    * @property {module:api/AccountsApi}
    */
    AccountsApi,

    /**
    * The BeverageApi service constructor.
    * @property {module:api/BeverageApi}
    */
    BeverageApi,

    /**
    * The BierwartApi service constructor.
    * @property {module:api/BierwartApi}
    */
    BierwartApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
