/*
 * Bierwart API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateAccountMovementBody model module.
 * @module model/CreateAccountMovementBody
 * @version 0.1
 */
export class CreateAccountMovementBody {
  /**
   * Constructs a new <code>CreateAccountMovementBody</code>.
   * @alias module:model/CreateAccountMovementBody
   * @class
   * @param idAccount {Number} id of account
   * @param amount {Number} money to be transfered
   */
  constructor(idAccount, amount) {
    this.idAccount = idAccount;
    this.amount = amount;
  }

  /**
   * Constructs a <code>CreateAccountMovementBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateAccountMovementBody} obj Optional instance to populate.
   * @return {module:model/CreateAccountMovementBody} The populated <code>CreateAccountMovementBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateAccountMovementBody();
      if (data.hasOwnProperty('id_account'))
        obj.idAccount = ApiClient.convertToType(data['id_account'], 'Number');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('is_deposit'))
        obj.isDeposit = ApiClient.convertToType(data['is_deposit'], 'Boolean');
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
    }
    return obj;
  }
}

/**
 * id of account
 * @member {Number} idAccount
 */
CreateAccountMovementBody.prototype.idAccount = undefined;

/**
 * money to be transfered
 * @member {Number} amount
 */
CreateAccountMovementBody.prototype.amount = undefined;

/**
 * depositing money?
 * @member {Boolean} isDeposit
 * @default false
 */
CreateAccountMovementBody.prototype.isDeposit = false;

/**
 * comment to be added to transfer
 * @member {String} comment
 */
CreateAccountMovementBody.prototype.comment = undefined;

