/*
 * Bierwart API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateDrinkTypeBody model module.
 * @module model/CreateDrinkTypeBody
 * @version 0.1
 */
export class CreateDrinkTypeBody {
  /**
   * Constructs a new <code>CreateDrinkTypeBody</code>.
   * @alias module:model/CreateDrinkTypeBody
   * @class
   * @param name {String} Name of the drinktype 
   * @param price {Number} Price of this type in €-cents
   */
  constructor(name, price) {
    this.name = name;
    this.price = price;
  }

  /**
   * Constructs a <code>CreateDrinkTypeBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateDrinkTypeBody} obj Optional instance to populate.
   * @return {module:model/CreateDrinkTypeBody} The populated <code>CreateDrinkTypeBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateDrinkTypeBody();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
    }
    return obj;
  }
}

/**
 * Name of the drinktype 
 * @member {String} name
 */
CreateDrinkTypeBody.prototype.name = undefined;

/**
 * Price of this type in €-cents
 * @member {Number} price
 */
CreateDrinkTypeBody.prototype.price = undefined;

