/*
 * Bierwart API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OrderBeverageBody model module.
 * @module model/OrderBeverageBody
 * @version 0.1
 */
export class OrderBeverageBody {
  /**
   * Constructs a new <code>OrderBeverageBody</code>.
   * @alias module:model/OrderBeverageBody
   * @class
   * @param idUser {Number} id of user
   * @param idBeverage {Boolean} which kind of drink should be moved?
   * @param quantity {Number} how many drinks should be moved?
   */
  constructor(idUser, idBeverage, quantity) {
    this.idUser = idUser;
    this.idBeverage = idBeverage;
    this.quantity = quantity;
  }

  /**
   * Constructs a <code>OrderBeverageBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderBeverageBody} obj Optional instance to populate.
   * @return {module:model/OrderBeverageBody} The populated <code>OrderBeverageBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderBeverageBody();
      if (data.hasOwnProperty('id_user'))
        obj.idUser = ApiClient.convertToType(data['id_user'], 'Number');
      if (data.hasOwnProperty('id_beverage'))
        obj.idBeverage = ApiClient.convertToType(data['id_beverage'], 'Boolean');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
    }
    return obj;
  }
}

/**
 * id of user
 * @member {Number} idUser
 */
OrderBeverageBody.prototype.idUser = undefined;

/**
 * which kind of drink should be moved?
 * @member {Boolean} idBeverage
 */
OrderBeverageBody.prototype.idBeverage = undefined;

/**
 * how many drinks should be moved?
 * @member {Number} quantity
 */
OrderBeverageBody.prototype.quantity = undefined;

